"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    q: "How accurate is the AI pricing?",
    a: "Our AI is pre-trained on thousands of HVAC, plumbing, and electrical jobs. On average, quotes generated by QuoteFlow require less than 5% manual adjustment. You always review and approve before sending.",
  },
  {
    q: "What if I have no internet at the job site?",
    a: "QuoteFlow works fully offline. Capture photos and voice notes, create quotes, and everything syncs automatically when you reconnect.",
  },
  {
    q: "Can I use my own pricing?",
    a: "Absolutely. You control all pricing. Set custom labor rates, material markups, and per-job adjustments. The AI suggests pricing, you decide.",
  },
  {
    q: "How does the free trial work?",
    a: "3-day free trial, no credit card required. Full access to all features. If you love it, choose a plan. If not, no charge.",
  },
  {
    q: "What happens to my data if I cancel?",
    a: "You own your data. Export everything before canceling, or delete it permanently. We don\u2019t keep anything after account deletion.",
  },
  {
    q: "Does QuoteFlow integrate with QuickBooks?",
    a: "Yes, on Enterprise plans. Quotes sync directly to QuickBooks for invoicing.",
  },
  {
    q: "Can multiple team members use one account?",
    a: "Yes. Team and Enterprise plans support multiple users with role-based permissions.",
  },
  {
    q: "Is my customer data secure?",
    a: "Yes. All data is encrypted, GDPR/CCPA compliant, and protected by row-level security. We never access your customer information.",
  },
];

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="bg-[#f8f9fa] py-20 sm:py-28">
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <h2 className="text-center text-3xl font-bold text-gray-900 sm:text-4xl">
          Frequently Asked Questions
        </h2>

        <div className="mt-12 space-y-3">
          {faqs.map((faq, i) => (
            <div
              key={faq.q}
              className="overflow-hidden rounded-xl border-l-4 border-accent bg-white shadow-sm"
            >
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="flex w-full items-center justify-between px-6 py-5 text-left"
                aria-expanded={openIndex === i}
              >
                <span className="font-semibold text-gray-900">{faq.q}</span>
                <ChevronDown
                  className={`ml-4 h-5 w-5 shrink-0 text-accent transition-transform duration-300 ${
                    openIndex === i ? "rotate-180" : ""
                  }`}
                />
              </button>
              <div
                className={`grid transition-all duration-300 ease-in-out ${
                  openIndex === i
                    ? "grid-rows-[1fr] opacity-100"
                    : "grid-rows-[0fr] opacity-0"
                }`}
              >
                <div className="overflow-hidden">
                  <p className="px-6 pb-5 leading-relaxed text-gray-600">
                    {faq.a}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
